### ISSUE TITLE
Line 25 print error

### ISSUE THREAD

**Issue by kelper1** [hmittal657/laziness#2]
when I tried to run this through Windows Powershell, it said this
 ```
 File "insta_text_dms_extraction.py", line 25
    print "Index: ",x
```
I'm new to everything here, never really coded here so I don't know what to do to fix this at all even though it seems like it's a simple problem or even a problem with software

**Comment by luisk06** [comment]
> when I tried to run this through Windows Powershell, it said this
> 
> ```
> File "insta_text_dms_extraction.py", line 25
>    print "Index: ",x
> ```
> 
> I'm new to everything here, never really coded here so I don't know what to do to fix this at all even though it seems like it's a simple problem or even a problem with software

print ("Index: ",x), and the same with the others print steps

**Comment by hmittal657** [comment]
Please refer README for updated instructions on browsing instagram chats. This file is no longer maintained
